<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>data_collection</name>
  <version>0.0.0</version>
  <description>Data collection tools including video recording and image extraction</description>
  <maintainer email="anton.deguet@jhu.edu">Anton Deguet</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>image_transport</depend>
  <depend>camera_info_manager</depend>
  <depend>rosbag2_cpp</depend>
  <build_depend>ament_cmake</build_depend>
  <build_depend>ament_cmake_python</build_depend>
  <build_depend>pkg-config</build_depend>
  <build_depend>gstreamer-1.0</build_depend>
  <build_depend>gstreamer-video-1.0</build_depend>
  <build_depend>gstreamer-app-1.0</build_depend>
  <build_depend>gtk+-3.0</build_depend>
  <build_depend>gtkmm-3.0</build_depend>
  <build_depend>jsoncpp</build_depend>
  <exec_depend>python3-opencv</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>gstreamer-1.0</exec_depend>
  <exec_depend>gstreamer-video-1.0</exec_depend>
  <exec_depend>gstreamer-app-1.0</exec_depend>
  <exec_depend>gtk+-3.0</exec_depend>
  <exec_depend>gtkmm-3.0</exec_depend>
  <exec_depend>jsoncpp</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
